# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "humin"
license = "MIT"
licenselink = "https://github.com/ritchie46/humin/blob/master/LICENSE.md"
description = "Minimal blog theme for hugo based on Hucore"
homepage = "https://github.com/ritchie46/humin"
tags = ["blog", "font awesome", "highlight.js"]
features = ["html5", "css3", "tags"]
min_version = 0.16

[author]
  name = "Ritchie Vink"
  homepage = "https://github.com/ritchie46"
